"""
db.py
-----
SQLite schema and helpers for Chess Signal analytics.

Stores raw game data and stats snapshots privately.
Public-facing output is generated by sanitizer.py (not yet built).
"""

import sqlite3
from pathlib import Path
from datetime import datetime

DB_PATH = Path(__file__).parent / "chess_signal.db"

SCHEMA = """
CREATE TABLE IF NOT EXISTS games (
    id              INTEGER PRIMARY KEY,
    source          TEXT NOT NULL,           -- 'chess_com' or 'lichess'
    account         TEXT NOT NULL,           -- which account
    game_id         TEXT,                    -- Chess.com game ID or Lichess game ID
    opponent        TEXT,
    my_rating       INTEGER,
    opponent_rating INTEGER,
    result          TEXT,                    -- 'win', 'loss', 'draw'
    time_control    TEXT,                    -- '10+0', '15+10', etc.
    time_class      TEXT,                    -- 'rapid', 'blitz', 'bullet', 'daily'
    opening         TEXT,
    played_at       TIMESTAMP,
    pgn             TEXT,
    imported_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stats_snapshots (
    id          INTEGER PRIMARY KEY,
    source      TEXT NOT NULL,
    account     TEXT NOT NULL,
    time_class  TEXT,                        -- 'rapid', 'blitz', 'bullet'
    rating      INTEGER,
    record_win  INTEGER,
    record_loss INTEGER,
    record_draw INTEGER,
    captured_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_games_source_account ON games(source, account);
CREATE INDEX IF NOT EXISTS idx_games_played_at ON games(played_at);
CREATE INDEX IF NOT EXISTS idx_stats_source_account ON stats_snapshots(source, account);
"""


def get_db(db_path: Path | None = None) -> sqlite3.Connection:
    """Get a database connection, creating the DB if needed."""
    path = db_path or DB_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(path))
    conn.row_factory = sqlite3.Row
    conn.executescript(SCHEMA)
    return conn


def insert_game(conn: sqlite3.Connection, game: dict) -> int:
    """Insert a game record. Returns the row ID."""
    cursor = conn.execute(
        """INSERT INTO games
           (source, account, game_id, opponent, my_rating, opponent_rating,
            result, time_control, time_class, opening, played_at, pgn)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
        (
            game["source"],
            game["account"],
            game.get("game_id"),
            game.get("opponent"),
            game.get("my_rating"),
            game.get("opponent_rating"),
            game["result"],
            game.get("time_control"),
            game.get("time_class"),
            game.get("opening"),
            game.get("played_at"),
            game.get("pgn"),
        ),
    )
    conn.commit()
    return cursor.lastrowid


def insert_stats(conn: sqlite3.Connection, stats: dict) -> int:
    """Insert a stats snapshot. Returns the row ID."""
    cursor = conn.execute(
        """INSERT INTO stats_snapshots
           (source, account, time_class, rating, record_win, record_loss, record_draw)
           VALUES (?, ?, ?, ?, ?, ?, ?)""",
        (
            stats["source"],
            stats["account"],
            stats.get("time_class"),
            stats.get("rating"),
            stats.get("record_win"),
            stats.get("record_loss"),
            stats.get("record_draw"),
        ),
    )
    conn.commit()
    return cursor.lastrowid


def get_games(
    conn: sqlite3.Connection,
    source: str | None = None,
    account: str | None = None,
    time_class: str | None = None,
    limit: int = 100,
) -> list[sqlite3.Row]:
    """Query games with optional filters."""
    query = "SELECT * FROM games WHERE 1=1"
    params: list = []
    if source:
        query += " AND source = ?"
        params.append(source)
    if account:
        query += " AND account = ?"
        params.append(account)
    if time_class:
        query += " AND time_class = ?"
        params.append(time_class)
    query += " ORDER BY played_at DESC LIMIT ?"
    params.append(limit)
    return conn.execute(query, params).fetchall()


def get_latest_stats(conn: sqlite3.Connection, source: str, account: str) -> list[sqlite3.Row]:
    """Get the most recent stats snapshot for each time class."""
    return conn.execute(
        """SELECT * FROM stats_snapshots
           WHERE source = ? AND account = ?
           AND id IN (
               SELECT MAX(id) FROM stats_snapshots
               WHERE source = ? AND account = ?
               GROUP BY time_class
           )""",
        (source, account, source, account),
    ).fetchall()


def game_exists(conn: sqlite3.Connection, source: str, account: str, game_id: str) -> bool:
    """Check if a game already exists in the database."""
    row = conn.execute(
        "SELECT 1 FROM games WHERE source = ? AND account = ? AND game_id = ?",
        (source, account, game_id),
    ).fetchone()
    return row is not None


def get_last_played_at(conn: sqlite3.Connection, source: str, account: str) -> str | None:
    """Get the most recent game date for a source/account pair."""
    row = conn.execute(
        "SELECT MAX(played_at) FROM games WHERE source = ? AND account = ?",
        (source, account),
    ).fetchone()
    return row[0] if row and row[0] else None
